# Generated by Django 2.2.16 on 2020-10-31 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="health_status",
            field=models.TextField(blank=True, null=True),
        ),
    ]
