# Generated by Django 2.2.16 on 2020-10-31 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0002_profile_health_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='accessibility',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='health_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
